apiVersion: v1
kind: Service
metadata:
  # We need this suffix because the service env var KAFKA_PORT is reserved by the docker image.
  name: {{ .Values.kafka.service.name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.kafka.service.type }}
  ports:
  - port: {{ .Values.kafka.service.externalPort }}
    targetPort: {{ .Values.kafka.service.internalPort }}
    protocol: TCP
    name: kafka
{{ if eq .Values.kafka.service.type "NodePort" }}
    nodePort: {{ .Values.kafka.service.nodePort }}
{{ end }}
  selector:
    app: {{ template "fullname" . }}-kafka
