apiVersion: v1
kind: Service
metadata:
  name: {{ template "vault.fullname" . }}
  labels:
    app: {{ template "vault.name" . }}
    chart: {{ template "vault.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.internalPort }}
      targetPort: {{ .Values.service.ports.externalPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "vault.name" . }}
    release: {{ .Release.Name }}
  