{{- if .Values.service.create -}}
apiVersion: v1
kind: Service
metadata:
  name: furan
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: {{ .Values.service.name }}
    nodePort: {{ .Values.service.nodePort }}
  selector:
    appsel: furan
{{- end -}}