// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dollarshaveclub/furan/lib/github_fetch (interfaces: CodeFetcher)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
	io "io"
)

// MockCodeFetcher is a mock of CodeFetcher interface
type MockCodeFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockCodeFetcherMockRecorder
}

// MockCodeFetcherMockRecorder is the mock recorder for MockCodeFetcher
type MockCodeFetcherMockRecorder struct {
	mock *MockCodeFetcher
}

// NewMockCodeFetcher creates a new mock instance
func NewMockCodeFetcher(ctrl *gomock.Controller) *MockCodeFetcher {
	mock := &MockCodeFetcher{ctrl: ctrl}
	mock.recorder = &MockCodeFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockCodeFetcher) EXPECT() *MockCodeFetcherMockRecorder {
	return _m.recorder
}

// Get mocks base method
func (_m *MockCodeFetcher) Get(_param0 string, _param1 string, _param2 string) (io.Reader, error) {
	ret := _m.ctrl.Call(_m, "Get", _param0, _param1, _param2)
	ret0, _ := ret[0].(io.Reader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (_mr *MockCodeFetcherMockRecorder) Get(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Get", arg0, arg1, arg2)
}

// GetCommitSHA mocks base method
func (_m *MockCodeFetcher) GetCommitSHA(_param0 string, _param1 string, _param2 string) (string, error) {
	ret := _m.ctrl.Call(_m, "GetCommitSHA", _param0, _param1, _param2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommitSHA indicates an expected call of GetCommitSHA
func (_mr *MockCodeFetcherMockRecorder) GetCommitSHA(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetCommitSHA", arg0, arg1, arg2)
}
