// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dollarshaveclub/furan/lib/datalayer (interfaces: DataLayer)

package mocks

import (
	lib "github.com/dollarshaveclub/furan/generated/lib"
	gocql "github.com/gocql/gocql"
	gomock "github.com/golang/mock/gomock"
)

// MockDataLayer is a mock of DataLayer interface
type MockDataLayer struct {
	ctrl     *gomock.Controller
	recorder *MockDataLayerMockRecorder
}

// MockDataLayerMockRecorder is the mock recorder for MockDataLayer
type MockDataLayerMockRecorder struct {
	mock *MockDataLayer
}

// NewMockDataLayer creates a new mock instance
func NewMockDataLayer(ctrl *gomock.Controller) *MockDataLayer {
	mock := &MockDataLayer{ctrl: ctrl}
	mock.recorder = &MockDataLayerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockDataLayer) EXPECT() *MockDataLayerMockRecorder {
	return _m.recorder
}

// CreateBuild mocks base method
func (_m *MockDataLayer) CreateBuild(_param0 *lib.BuildRequest) (gocql.UUID, error) {
	ret := _m.ctrl.Call(_m, "CreateBuild", _param0)
	ret0, _ := ret[0].(gocql.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBuild indicates an expected call of CreateBuild
func (_mr *MockDataLayerMockRecorder) CreateBuild(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CreateBuild", arg0)
}

// DeleteBuild mocks base method
func (_m *MockDataLayer) DeleteBuild(_param0 gocql.UUID) error {
	ret := _m.ctrl.Call(_m, "DeleteBuild", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBuild indicates an expected call of DeleteBuild
func (_mr *MockDataLayerMockRecorder) DeleteBuild(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeleteBuild", arg0)
}

// GetBuildByID mocks base method
func (_m *MockDataLayer) GetBuildByID(_param0 gocql.UUID) (*lib.BuildStatusResponse, error) {
	ret := _m.ctrl.Call(_m, "GetBuildByID", _param0)
	ret0, _ := ret[0].(*lib.BuildStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBuildByID indicates an expected call of GetBuildByID
func (_mr *MockDataLayerMockRecorder) GetBuildByID(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetBuildByID", arg0)
}

// GetBuildOutput mocks base method
func (_m *MockDataLayer) GetBuildOutput(_param0 gocql.UUID, _param1 string) ([]lib.BuildEvent, error) {
	ret := _m.ctrl.Call(_m, "GetBuildOutput", _param0, _param1)
	ret0, _ := ret[0].([]lib.BuildEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBuildOutput indicates an expected call of GetBuildOutput
func (_mr *MockDataLayerMockRecorder) GetBuildOutput(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetBuildOutput", arg0, arg1)
}

// SaveBuildOutput mocks base method
func (_m *MockDataLayer) SaveBuildOutput(_param0 gocql.UUID, _param1 []lib.BuildEvent, _param2 string) error {
	ret := _m.ctrl.Call(_m, "SaveBuildOutput", _param0, _param1, _param2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveBuildOutput indicates an expected call of SaveBuildOutput
func (_mr *MockDataLayerMockRecorder) SaveBuildOutput(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SaveBuildOutput", arg0, arg1, arg2)
}

// SetBuildCompletedTimestamp mocks base method
func (_m *MockDataLayer) SetBuildCompletedTimestamp(_param0 gocql.UUID) error {
	ret := _m.ctrl.Call(_m, "SetBuildCompletedTimestamp", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBuildCompletedTimestamp indicates an expected call of SetBuildCompletedTimestamp
func (_mr *MockDataLayerMockRecorder) SetBuildCompletedTimestamp(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetBuildCompletedTimestamp", arg0)
}

// SetBuildFlags mocks base method
func (_m *MockDataLayer) SetBuildFlags(_param0 gocql.UUID, _param1 map[string]bool) error {
	ret := _m.ctrl.Call(_m, "SetBuildFlags", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBuildFlags indicates an expected call of SetBuildFlags
func (_mr *MockDataLayerMockRecorder) SetBuildFlags(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetBuildFlags", arg0, arg1)
}

// SetBuildState mocks base method
func (_m *MockDataLayer) SetBuildState(_param0 gocql.UUID, _param1 lib.BuildStatusResponse_BuildState) error {
	ret := _m.ctrl.Call(_m, "SetBuildState", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBuildState indicates an expected call of SetBuildState
func (_mr *MockDataLayerMockRecorder) SetBuildState(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetBuildState", arg0, arg1)
}

// SetBuildTimeMetric mocks base method
func (_m *MockDataLayer) SetBuildTimeMetric(_param0 gocql.UUID, _param1 string) error {
	ret := _m.ctrl.Call(_m, "SetBuildTimeMetric", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBuildTimeMetric indicates an expected call of SetBuildTimeMetric
func (_mr *MockDataLayerMockRecorder) SetBuildTimeMetric(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetBuildTimeMetric", arg0, arg1)
}

// SetDockerImageSizesMetric mocks base method
func (_m *MockDataLayer) SetDockerImageSizesMetric(_param0 gocql.UUID, _param1 int64, _param2 int64) error {
	ret := _m.ctrl.Call(_m, "SetDockerImageSizesMetric", _param0, _param1, _param2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDockerImageSizesMetric indicates an expected call of SetDockerImageSizesMetric
func (_mr *MockDataLayerMockRecorder) SetDockerImageSizesMetric(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetDockerImageSizesMetric", arg0, arg1, arg2)
}
