// Code generated by "stringer -type=buildStatus"; DO NOT EDIT

package cmd

import "fmt"

const _buildStatus_name = "buildingpushingpullingSquashedsuccessbuildFailurepushFailurepullSquashedFailure"

var _buildStatus_index = [...]uint8{0, 8, 15, 30, 37, 49, 60, 79}

func (i buildStatus) String() string {
	if i < 0 || i >= buildStatus(len(_buildStatus_index)-1) {
		return fmt.Sprintf("buildStatus(%d)", i)
	}
	return _buildStatus_name[_buildStatus_index[i]:_buildStatus_index[i+1]]
}
