# Default values for scylladb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: scylladb/scylla
  tag: 2.1.3
  pullPolicy: IfNotPresent

config:
  overprovisioned: 1

service:
  cqlPort: 9042
  
resources: {}