apiVersion: v1
kind: Service
metadata:
  name: {{ template "scylladb.fullname" . }}
  labels:
    app: {{ template "scylladb.name" . }}
    chart: {{ template "scylladb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.cqlPort }}
      name: cql
  selector:
    app: {{ template "scylladb.name" . }}
    release: {{ .Release.Name }}